// Data for car makes and models (alphabetized)
export const makesAndModels: Record<string, string[]> = {
  'acura': ['ILX', 'Integra', 'MDX', 'NSX', 'RDX', 'RLX', 'RSX', 'TLX', 'TSX', 'ZDX'],
  'alfa romeo': ['4C', 'Giulia', 'Giulietta', 'MiTo', 'Spider', 'Stelvio', 'Tonale'],
  'aston martin': ['DB11', 'DB12', 'DBS', 'DBX', 'Valhalla', 'Valkyrie', 'Vantage'],
  'audi': ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'e-tron', 'e-tron GT', 'Q2', 'Q3', 'Q4', 'Q5', 'Q7', 'Q8', 'R8', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'TT'],
  'bentley': ['Bentayga', 'Continental GT', 'Flying Spur', 'Mulsanne'],
  'bmw': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'i3', 'i4', 'i7', 'i8', 'iX', 'M2', 'M3', 'M4', 'M5', 'M8', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4'],
  'bugatti': ['Chiron', 'Veyron'],
  'buick': ['Cascada', 'Enclave', 'Encore', 'Encore GX', 'Envision', 'LaCrosse', 'Lucerne', 'Regal', 'Verano'],
  'cadillac': ['ATS', 'CT4', 'CT5', 'CTS', 'ELR', 'Escalade', 'LYRIQ', 'SRX', 'XT4', 'XT5', 'XT6', 'XTS'],
  'chevrolet': ['Blazer', 'Bolt', 'Camaro', 'Colorado', 'Corvette', 'Equinox', 'Express', 'Impala', 'Malibu', 'Silverado', 'Sonic', 'Spark', 'Suburban', 'Tahoe', 'Trailblazer', 'Traverse', 'Trax'],
  'chrysler': ['200', '300', 'Pacifica', 'PT Cruiser', 'Sebring', 'Town & Country', 'Voyager'],
  'dodge': ['Avenger', 'Challenger', 'Charger', 'Dart', 'Durango', 'Grand Caravan', 'Journey', 'Nitro', 'Viper'],
  'ferrari': ['296 GTB', '458', '488', 'California', 'F8', 'LaFerrari', 'Portofino', 'Purosangue', 'Roma', 'SF90'],
  'fiat': ['124 Spider', '500', '500L', '500X', 'Panda', 'Tipo'],
  'ford': ['Bronco', 'EcoSport', 'Edge', 'Escape', 'Expedition', 'Explorer', 'F-150', 'F-250', 'F-350', 'Fiesta', 'Focus', 'Fusion', 'Lightning', 'Maverick', 'Mustang', 'Mustang Mach-E', 'Ranger', 'Transit'],
  'genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  'gmc': ['Acadia', 'Canyon', 'Envoy', 'Hummer EV', 'Savana', 'Sierra', 'Terrain', 'Yukon'],
  'honda': ['Accord', 'Civic', 'Clarity', 'CR-V', 'CR-Z', 'Crosstour', 'Element', 'Fit', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Prologue', 'Ridgeline'],
  'hyundai': ['Accent', 'Azera', 'Elantra', 'Genesis', 'IONIQ', 'IONIQ 5', 'IONIQ 6', 'Kona', 'Nexo', 'Palisade', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster', 'Venue'],
  'infiniti': ['FX35', 'G35', 'G37', 'JX35', 'M35', 'Q50', 'Q60', 'QX50', 'QX55', 'QX60', 'QX80'],
  'jaguar': ['E-PACE', 'F-PACE', 'F-TYPE', 'I-PACE', 'XE', 'XF', 'XJ'],
  'jeep': ['Cherokee', 'Commander', 'Compass', 'Gladiator', 'Grand Cherokee', 'Grand Wagoneer', 'Liberty', 'Patriot', 'Renegade', 'Wagoneer', 'Wrangler'],
  'kia': ['Cadenza', 'Carnival', 'EV6', 'EV9', 'Forte', 'K5', 'Niro', 'Optima', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Telluride'],
  'lamborghini': ['Aventador', 'Huracan', 'Revuelto', 'Urus'],
  'land rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  'lexus': ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RC', 'RZ', 'RX', 'SC', 'UX'],
  'lincoln': ['Aviator', 'Continental', 'Corsair', 'MKC', 'MKT', 'MKX', 'MKZ', 'Nautilus', 'Navigator', 'Town Car'],
  'lotus': ['Elise', 'Emira', 'Evija', 'Evora', 'Exige'],
  'lucid': ['Air', 'Gravity'],
  'maserati': ['Ghibli', 'Grecale', 'Levante', 'MC20', 'Quattroporte'],
  'mazda': ['CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-9', 'Mazda3', 'Mazda6', 'MX-30', 'MX-5 Miata', 'RX-7', 'RX-8'],
  'mclaren': ['570S', '720S', 'Artura', 'Elva', 'GT', 'P1', 'Senna'],
  'mercedes': ['A-Class', 'AMG GT', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'EQE', 'EQS', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'Maybach', 'S-Class', 'SL', 'SLC', 'V-Class'],
  'mini': ['Clubman', 'Convertible', 'Cooper', 'Countryman', 'Paceman'],
  'mitsubishi': ['Eclipse Cross', 'Lancer', 'Mirage', 'Outlander', 'Outlander Sport', 'Pajero', 'Raider'],
  'nissan': ['370Z', 'Altima', 'Armada', 'Frontier', 'GT-R', 'Juke', 'Kicks', 'Leaf', 'Maxima', 'Murano', 'Pathfinder', 'Quest', 'Rogue', 'Rogue Sport', 'Sentra', 'Titan', 'Versa', 'Z'],
  'pagani': ['Huayra', 'Utopia', 'Zonda'],
  'polestar': ['Polestar 1', 'Polestar 2', 'Polestar 3', 'Polestar 4'],
  'porsche': ['718 Boxster', '718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  'ram': ['1500', '2500', '3500', 'Dakota', 'ProMaster', 'ProMaster City'],
  'rivian': ['R1S', 'R1T'],
  'rolls-royce': ['Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Spectre', 'Wraith'],
  'saab': ['9-3', '9-5'],
  'saturn': ['Astra', 'Aura', 'Ion', 'Outlook', 'Sky', 'Vue'],
  'scion': ['FR-S', 'iA', 'iM', 'tC', 'xA', 'xB', 'xD'],
  'subaru': ['Ascent', 'Baja', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'Solterra', 'Tribeca', 'WRX'],
  'suzuki': ['Grand Vitara', 'Kizashi', 'SX4', 'Swift', 'Vitara'],
  'tesla': ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster'],
  'toyota': ['4Runner', 'Avalon', 'bZ4X', 'C-HR', 'Camry', 'Corolla', 'GR86', 'Highlander', 'Land Cruiser', 'Prius', 'RAV4', 'Sequoia', 'Sienna', 'Supra', 'Tacoma', 'Tundra', 'Venza'],
  'volkswagen': ['Arteon', 'Atlas', 'Beetle', 'CC', 'Golf', 'Golf GTI', 'Golf R', 'ID.4', 'ID.Buzz', 'Jetta', 'Passat', 'Taos', 'Tiguan', 'Touareg'],
  'volvo': ['C40', 'S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90']
};

// Base values for different makes (for valuation)
export const carBaseValues: Record<string, number> = {
  'acura': 35000,
  'alfa romeo': 40000,
  'aston martin': 180000,
  'audi': 42000,
  'bentley': 190000,
  'bmw': 45000,
  'bugatti': 2500000,
  'buick': 30000,
  'cadillac': 45000,
  'chevrolet': 27000,
  'chrysler': 28000,
  'dodge': 29000,
  'ferrari': 250000,
  'fiat': 22000,
  'ford': 28000,
  'genesis': 43000,
  'gmc': 32000,
  'honda': 23000,
  'hyundai': 20000,
  'infiniti': 36000,
  'jaguar': 48000,
  'jeep': 32000,
  'kia': 19000,
  'lamborghini': 280000,
  'land rover': 55000,
  'lexus': 40000,
  'lincoln': 42000,
  'lotus': 85000,
  'lucid': 80000,
  'maserati': 80000,
  'mazda': 23000,
  'mclaren': 210000,
  'mercedes': 50000,
  'mini': 28000,
  'mitsubishi': 22000,
  'nissan': 22000,
  'pagani': 1800000,
  'polestar': 58000,
  'porsche': 65000,
  'ram': 33000,
  'rivian': 75000,
  'rolls-royce': 350000,
  'saab': 18000,
  'saturn': 15000,
  'scion': 16000,
  'subaru': 24000,
  'suzuki': 18000,
  'tesla': 52000,
  'toyota': 25000,
  'volkswagen': 26000,
  'volvo': 38000,
  'default': 25000
};

// Condition adjustment factors
export const conditionFactors: Record<string, number> = {
  'great': 0.05,     // +5% for great condition
  'good': 0,         // No adjustment for good (standard) condition
  'fair': -0.05,     // -5% for fair condition
  'bad': -0.15,      // -15% for bad condition
  'non-drivable': -0.40, // -40% for non-drivable condition
};
